# Generated by Django 4.1.5 on 2024-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='goal',
            field=models.CharField(default='', max_length=100),
        ),
    ]
