# Generated by Django 4.1.5 on 2024-04-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movieType', models.CharField(max_length=100)),
                ('movieName', models.CharField(max_length=100)),
            ],
        ),
    ]
